// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCSK8dUTBc6XR--sHy9zotpun-QSXL_grw',
    appId: '1:532269469513:web:0c47a52e6532b66ea01498',
    messagingSenderId: '532269469513',
    projectId: 'obd-marcos',
    authDomain: 'obd-marcos.firebaseapp.com',
    storageBucket: 'obd-marcos.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBzZ9-J4bRWGx9YRnjfI8unv3RdT7TO7lg',
    appId: '1:532269469513:android:4d76119514e24219a01498',
    messagingSenderId: '532269469513',
    projectId: 'obd-marcos',
    storageBucket: 'obd-marcos.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB3HWB8IhF1IUeMkXVKmmWZUkgx58owmgE',
    appId: '1:532269469513:ios:fafab477f9467f3ba01498',
    messagingSenderId: '532269469513',
    projectId: 'obd-marcos',
    storageBucket: 'obd-marcos.firebasestorage.app',
    iosBundleId: 'marcos.vinagre.proytectoFinDeCurso',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB3HWB8IhF1IUeMkXVKmmWZUkgx58owmgE',
    appId: '1:532269469513:ios:fafab477f9467f3ba01498',
    messagingSenderId: '532269469513',
    projectId: 'obd-marcos',
    storageBucket: 'obd-marcos.firebasestorage.app',
    iosBundleId: 'marcos.vinagre.proytectoFinDeCurso',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCSK8dUTBc6XR--sHy9zotpun-QSXL_grw',
    appId: '1:532269469513:web:45f91c83dcf5fbfaa01498',
    messagingSenderId: '532269469513',
    projectId: 'obd-marcos',
    authDomain: 'obd-marcos.firebaseapp.com',
    storageBucket: 'obd-marcos.firebasestorage.app',
  );
}
